#!/bin/sh

sed -i 's/.*CONFIG_PACKAGE_aws-iot-sdk is not set.*//g' .config
sed -i 's/.*CONFIG_PACKAGE_aws-iot-sdk-apps is not set.*//g' .config

cat <<EOF  >> .config
CONFIG_PACKAGE_aws-iot-sdk=y
CONFIG_PACKAGE_aws-iot-sdk-apps=y

#
# Configuration
#
CONFIG_AWS_IOT_MQTT_HOST="A1EY1YJM24R9FH.iot.us-east-1.amazonaws.com"
CONFIG_AWS_IOT_MQTT_PORT=8883
CONFIG_AWS_IOT_MQTT_CLIENT_ID="c-sdk-client-id"
CONFIG_AWS_IOT_MY_THING_NAME="AWS-IoT-C-SDK"
CONFIG_AWS_IOT_MQTT_TX_BUF_LEN=512
CONFIG_AWS_IOT_MQTT_RX_BUF_LEN=512
CONFIG_AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS=5
CONFIG_SHADOW_MAX_SIZE_OF_RX_BUFFER=513
CONFIG_MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES=80
CONFIG_MAX_SIZE_CLIENT_ID_WITH_SEQUENCE=90
CONFIG_MAX_SIZE_CLIENT_TOKEN_CLIENT_SEQUENCE=110
CONFIG_MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME=10
CONFIG_MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME=10
CONFIG_MAX_JSON_TOKEN_EXPECTED=120
CONFIG_MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME=60
CONFIG_MAX_SIZE_OF_THING_NAME=20
CONFIG_MAX_SHADOW_TOPIC_LENGTH_BYTES=80
CONFIG_AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL=20
CONFIG_AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL=1

EOF
